# Generated by Django 5.1 on 2024-08-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
