# Generated by Django 5.1 on 2024-08-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.person'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.person'),
        ),
    ]
