# Generated by Django 5.1 on 2024-08-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTags',
            new_name='CourseTag',
        ),
    ]
