# Generated by Django 5.1 on 2024-08-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Academic Unit Type',
                'verbose_name_plural': 'Academic Unit Types',
            },
        ),
        migrations.CreateModel(
            name='EducationalCredentialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('abbreviation', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Educational Credential Type',
                'verbose_name_plural': 'Educational Credential Types',
            },
        ),
        migrations.CreateModel(
            name='LocationAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_institution', models.BooleanField(default=False)),
                ('attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('academic_levels', models.ManyToManyField(related_name='academic_units', to='academic_structure.academiclevel')),
                ('superior_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_units', to='academic_structure.academicunit')),
                ('unit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_units', to='academic_structure.academicunittype')),
            ],
            options={
                'verbose_name': 'Academic Unit',
                'verbose_name_plural': 'Academic Units',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_structure.academiccalendar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_structure.academicperiodtype')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_structure.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('include_type_in_description', models.BooleanField(default=False)),
                ('educational_credential_usage', models.CharField(blank=True, choices=[('External', 'External'), ('Internal', 'Internal')], max_length=255, null=True)),
                ('credential_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_credentials', to='academic_structure.educationalcredentialtype')),
            ],
            options={
                'verbose_name': 'Educational Credential',
                'verbose_name_plural': 'Educational Credentials',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('usage', models.CharField(choices=[('Campus', 'Campus'), ('Instructional', 'Instructional'), ('Housing', 'Housing')], default='Instructional', max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('instructional_use_only', models.BooleanField(default=False)),
                ('owning_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_structure.academicunit')),
                ('superior_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_locations', to='academic_structure.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='LocationAttributeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.location')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.locationattributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramOfStudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('credential_granting', models.BooleanField(default=False)),
                ('concentration_possible', models.BooleanField(default=False)),
                ('can_stand_alone', models.BooleanField(default=False)),
                ('levels_offered_at', models.ManyToManyField(related_name='program_of_study_types', to='academic_structure.academiclevel')),
            ],
            options={
                'verbose_name': 'Program of Study Type',
                'verbose_name_plural': 'Program of Study Types',
            },
        ),
        migrations.CreateModel(
            name='ProgramOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('first_entry_date', models.DateField(blank=True, null=True)),
                ('academic_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_of_study', to='academic_structure.academiclevel')),
                ('coordinating_academic_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinating_programs_of_study', to='academic_structure.academicunit')),
                ('educational_credentials', models.ManyToManyField(related_name='programs_of_study', to='academic_structure.educationalcredential')),
                ('owning_academic_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_of_study', to='academic_structure.academicunit')),
                ('program_of_study_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_of_studies', to='academic_structure.programofstudytype')),
            ],
            options={
                'verbose_name': 'Program of Study',
                'verbose_name_plural': 'Program of Studies',
            },
        ),
    ]
