# Generated by Django 5.1 on 2024-08-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcredential',
            name='abbreviation',
            field=models.CharField(default='BA', max_length=80),
            preserve_default=False,
        ),
    ]
