# Generated by Django 5.1 on 2024-08-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('impacts_gpa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grading Basis',
                'verbose_name_plural': 'Grading Bases',
            },
        ),
        migrations.CreateModel(
            name='GradingBasisValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('gpa_value', models.FloatField()),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='grading.gradingbasis')),
            ],
            options={
                'verbose_name': 'Grading Basis Value',
                'verbose_name_plural': 'Grading Basis Values',
            },
        ),
    ]
