# Generated by Django 5.1 on 2024-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingbasisvalue',
            name='gpa_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
